# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIQT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from os import mkdir
from shutil import rmtree
import computer
import server
import tor_network

try:
    mkdir("keys")
except FileExistsError:
    pass

try:
    rmtree("logs")
except FileNotFoundError:
    pass

mkdir("logs")


torNetwork = tor_network.TorNetwork([], [])

pc1 = computer.Computer("PC1", "1.112.11.69", torNetwork)
pc2 = computer.Computer("PC2", "11.22.33.44", torNetwork)
pc3 = computer.Computer("PC3", "04.03.02.01", torNetwork)

srv1 = server.Server("SRV1", "11.11.11.11", torNetwork)
srv2 = server.Server("SRV2", "22.22.22.22", torNetwork)
srv3 = server.Server("SRV3", "33.33.33.33", torNetwork)
srv4 = server.Server("SRV4", "44.44.44.44", torNetwork)
srv5 = server.Server("SRV5", "55.55.55.55", torNetwork)
srv6 = server.Server("SRV6", "66.66.66.66", torNetwork)
rmtree("keys")
rmtree("logs")


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1602, 1003)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 121, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.computerListButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.computerListButton.setObjectName("computerListButton")
        self.listButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.listButtonGroup.setObjectName("listButtonGroup")
        self.listButtonGroup.addButton(self.computerListButton)
        self.verticalLayout.addWidget(self.computerListButton)
        self.serverListButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.serverListButton.setObjectName("serverListButton")
        self.listButtonGroup.addButton(self.serverListButton)
        self.verticalLayout.addWidget(self.serverListButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(120, 0, 141, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.listComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.listComboBox.setObjectName("listComboBox")
        self.verticalLayout_2.addWidget(self.listComboBox)
        self.removeButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeButton.setGeometry(QtCore.QRect(0, 70, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.removeButton.setFont(font)
        self.removeButton.setObjectName("removeButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 150, 261, 811))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(0, 150, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(0, 190, 261, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(0, 230, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 270, 261, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(0, 30, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.createServerButton = QtWidgets.QRadioButton(self.groupBox)
        self.createServerButton.setGeometry(QtCore.QRect(0, 70, 261, 41))
        self.createServerButton.setObjectName("createServerButton")
        self.createButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.createButtonGroup.setObjectName("createButtonGroup")
        self.createButtonGroup.addButton(self.createServerButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(0, 110, 261, 41))
        self.radioButton_2.setObjectName("radioButton_2")
        self.createButtonGroup.addButton(self.radioButton_2)
        self.createButton = QtWidgets.QPushButton(self.groupBox)
        self.createButton.setGeometry(QtCore.QRect(0, 350, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.createButton.setFont(font)
        self.createButton.setObjectName("createButton")
        self.randomAddress = QtWidgets.QPushButton(self.groupBox)
        self.randomAddress.setGeometry(QtCore.QRect(0, 310, 261, 41))
        self.randomAddress.setObjectName("randomAddress")
        self.terminalEntry = QtWidgets.QListView(self.centralwidget)
        self.terminalEntry.setGeometry(QtCore.QRect(260, 30, 1341, 121))
        self.terminalEntry.setStyleSheet("")
        self.terminalEntry.setObjectName("terminalEntry")
        self.terminal = QtWidgets.QLineEdit(self.centralwidget)
        self.terminal.setGeometry(QtCore.QRect(260, 0, 1251, 31))
        self.terminal.setObjectName("terminal")
        self.terminalEnterButton = QtWidgets.QPushButton(self.centralwidget)
        self.terminalEnterButton.setGeometry(QtCore.QRect(1510, 0, 91, 31))
        self.terminalEnterButton.setObjectName("terminalEnterButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1602, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.computerListButton.clicked.connect(lambda: self.clickedComputerListButton(torNetwork))
        self.serverListButton.clicked.connect(lambda: self.clickedServerListButton(torNetwork))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.computerListButton.setText(_translate("MainWindow", "Computers\' list"))
        self.serverListButton.setText(_translate("MainWindow", "Servers\' list"))
        self.label.setText(_translate("MainWindow", "Computer/Server List"))
        self.removeButton.setText(_translate("MainWindow", "Remove chosen device"))
        self.groupBox.setTitle(_translate("MainWindow", "Add new device"))
        self.label_3.setText(_translate("MainWindow", "Name:"))
        self.label_4.setText(_translate("MainWindow", "IP Adress:"))
        self.label_5.setText(_translate("MainWindow", "Choose device:"))
        self.createServerButton.setText(_translate("MainWindow", "Server"))
        self.radioButton_2.setText(_translate("MainWindow", "Computer"))
        self.createButton.setText(_translate("MainWindow", "Create new device"))
        self.randomAddress.setText(_translate("MainWindow", "Random address"))
        self.terminal.setText(_translate("MainWindow", "terminal"))
        self.terminalEnterButton.setText(_translate("MainWindow", "Enter"))


    def princik(self):
        print("Hello")


    def clickedComputerListButton(self, torNetwork=None):
        self.listComboBox.clear()
        for pc in torNetwork.computer_list:
            self.listComboBox.addItem(pc.name)

    def clickedServerListButton(self, torNetwork=None):
        self.listComboBox.clear()
        for serv in torNetwork.server_list:
            self.listComboBox.addItem(serv.name)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
